const mongoose = require('mongoose');

const PartnerSchema = new mongoose.Schema({
  tenantId:    { type: mongoose.Schema.Types.ObjectId, ref: 'Tenant', required: true, index: true },
  name:        { type: String, required: true, trim: true },
  slug:        { type: String, required: true, unique: true, lowercase: true, trim: true },
  ownerUserId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  status:      {
    type: String,
    enum: ['pending_request', 'rejected', 'approved', 'pending_quote', 'pending_payment', 'active', 'suspended'],
    default: 'pending_request',
  },
  mobile:      { type: String, default: '' },
  approvedAt:  { type: Date, default: null },
  rejectedAt:  { type: Date, default: null },
  rejectionReason: { type: String, default: '' },
  notes:       { type: String, default: '' },
  agreementDetails: { type: String, default: '' },
  agreementFileName: { type: String, default: '' },
  agreementFileType: { type: String, default: '' },
  agreementFilePath: { type: String, default: '' }, // relative path under /uploads/
  commissionPercent: { type: Number, default: 0 },
  partner_linked_account_id: { type: String, default: '', trim: true },
  capabilities: {
    createCompany:         { type: Boolean, default: false },
    downloadAgent:         { type: Boolean, default: false },
    subscriptionPurchase:  { type: Boolean, default: false },
  },
  agentPricing: {
    system: {
      monthly: { type: Number, min: 0 },
      yearly: { type: Number, min: 0 },
    },
    server: {
      monthly: { type: Number, min: 0 },
      yearly: { type: Number, min: 0 },
    },
    android: {
      monthly: { type: Number, min: 0 },
      yearly: { type: Number, min: 0 },
    },
    monthly:    { type: Number, default: 0 },
    sixMonthly: { type: Number, default: 0 },
    yearly:     { type: Number, default: 0 },
    currency:   { type: String, default: 'INR' },
    updatedAt:  { type: Date, default: null },
  },
  companyPricing: {
    newUser: {
      pricePerSystemMonthly: { type: Number, default: 0 },
      pricePerSystemYearly:  { type: Number, default: 0 },
      pricePerPhoneMonthly:  { type: Number, default: 0 },
      pricePerPhoneYearly:   { type: Number, default: 0 },
      pricePerServerMonthly: { type: Number, default: 0 },
      pricePerServerYearly:  { type: Number, default: 0 },
    },
    renewal: {
      pricePerSystemMonthly: { type: Number, default: 0 },
      pricePerSystemYearly:  { type: Number, default: 0 },
      pricePerPhoneMonthly:  { type: Number, default: 0 },
      pricePerPhoneYearly:   { type: Number, default: 0 },
      pricePerServerMonthly: { type: Number, default: 0 },
      pricePerServerYearly:  { type: Number, default: 0 },
    },
    history: [{
      userType: String,
      pricePerSystemMonthly: Number,
      pricePerSystemYearly: Number,
      pricePerPhoneMonthly: Number,
      pricePerPhoneYearly: Number,
      pricePerServerMonthly: Number,
      pricePerServerYearly: Number,
      changedAt: { type: Date, default: Date.now },
      changedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
      note: String,
    }],
    updatedAt: { type: Date, default: null },
  },
  agentLicenseSummary: {
    totalPurchased:    { type: Number, default: 0 },
    consumedLicenses:  { type: Number, default: 0 },
    remainingLicenses: { type: Number, default: 0 },
    activeLicenses:    { type: Number, default: 0 },
    inactiveLicenses:  { type: Number, default: 0 },
    lastExpiryAt:      { type: Date, default: null },
  },
  enterpriseLegacyConsumed: { type: Number, default: 0 },
  enterpriseAllocations: [{
    _id: false,
    orderId: { type: mongoose.Schema.Types.ObjectId, ref: 'EnterpriseOrder' },
    quantity: Number,
    allocatedAt: Date,
  }],
  agentLicenseAutoPay: {
    enabled:     { type: Boolean, default: false },
    paymentId:   { type: String, default: '' },
    enabledAt:   { type: Date, default: null },
    disabledAt:  { type: Date, default: null },
    feeInr:      { type: Number, default: 5 },
  },
  agentLicensePurchases: [{
    invoiceId:     { type: String, default: '' },
    orderId:       { type: String, default: '' },
    paymentId:     { type: String, default: '' },
    signature:     { type: String, default: '' },
    agentQuantity: { type: Number, default: 0 },
    agentType: { type: String, enum: ['system', 'server', 'android'], default: 'system' },
    consumedQuantity: { type: Number, default: 0 },
    planType:      { type: String, enum: ['monthly', 'six_monthly', 'yearly'], default: 'monthly' },
    pricePerAgent: { type: Number, default: 0 },
    amountInr:     { type: Number, default: 0 },
    autoPay:       { type: Boolean, default: false },
    autoPayFeeInr: { type: Number, default: 0 },
    buyDate:       { type: Date, default: null },
    expiryDate:    { type: Date, default: null },
    status:        { type: String, enum: ['active', 'inactive'], default: 'active' },
  }],
  resourceRequest: {
    status: { type: String, enum: ['none', 'pending', 'approved', 'rejected', 'negotiation'], default: 'none' },
    numberOfCompanies:     { type: Number, default: 0 },
    numberOfAgents:        { type: Number, default: 0 },
    expectedMonthlyVolume: { type: Number, default: 0 },
    proposedCommission:    { type: Number, default: 0 },
    additionalNotes:       { type: String, default: '' },
    adminNote:             { type: String, default: '' },
    requestedAt:           { type: Date, default: null },
    reviewedAt:            { type: Date, default: null },
    reviewedBy:            { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  },
  resourceRequestHistory: [{
    requestId:             { type: String, default: '' },
    status:                { type: String, enum: ['pending', 'approved', 'rejected', 'negotiation'], default: 'pending' },
    numberOfCompanies:     { type: Number, default: 0 },
    numberOfAgents:        { type: Number, default: 0 },
    expectedMonthlyVolume: { type: Number, default: 0 },
    proposedCommission:    { type: Number, default: 0 },
    additionalNotes:       { type: String, default: '' },
    adminNote:             { type: String, default: '' },
    requestedAt:           { type: Date, default: null },
    reviewedAt:            { type: Date, default: null },
    reviewedBy:            { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  }],
  plan: {
    type:          { type: String, default: 'enterprise' },
    billingCycle:  { type: String, enum: ['monthly', 'yearly'], default: 'monthly' },
    amountPaid:    { type: Number, default: 0 },
    paymentStatus: { type: String, enum: ['paid', 'unpaid', 'failed'], default: 'unpaid' },
    isActive:      { type: Boolean, default: false },
    autoPay:       { type: Boolean, default: false },
    autoPayMethod: { type: String, default: '' },
    startDate:     { type: Date, default: null },
    expiresAt:     { type: Date, default: null },
    requestStatus: { type: String, enum: ['none', 'requested', 'quoted', 'rejected', 'paid'], default: 'none' },
    request: {
      companyCount: { type: Number, default: 0 },
      systemCount:  { type: Number, default: 0 },
      serverCount:  { type: Number, default: 0 },
      phoneCount:   { type: Number, default: 0 },
      notes:        { type: String, default: '' },
      requestedAt:  { type: Date, default: null },
    },
    quote: {
      amountInr:    { type: Number, default: 0 },
      billingCycle: { type: String, enum: ['monthly', 'yearly'], default: 'monthly' },
      notes:        { type: String, default: '' },
      quotedBy:     { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
      quotedAt:     { type: Date, default: null },
    },
  },
  razorpay: {
    orderId:   { type: String },
    paymentId: { type: String },
    signature: { type: String },
    paidAt:    { type: Date },
  },
  profile: {
    designation:     { type: String, default: 'Partner Admin' },
    alternatePhone:  { type: String, default: '' },
    language:        { type: String, default: 'English' },
    timezone:        { type: String, default: '(GMT +05:30) Asia/Kolkata' },
    razorpayKeyId:    { type: String, default: '' },
    razorpaySecret:   { type: String, default: '' },
    bankAccount:      { type: String, default: '' },
    accountHolderName:{ type: String, default: '' },
    bankName:         { type: String, default: '' },
    accountNumber:    { type: String, default: '' },
    ifscCode:         { type: String, default: '' },
    branchName:       { type: String, default: '' },
    gstNumber:        { type: String, default: '' },
    panNumber:        { type: String, default: '' },
    kycStatus:        { type: String, enum: ['not_submitted', 'pending', 'verified', 'rejected'], default: 'not_submitted' },
    gstVerified:      { type: Boolean, default: false },
    panVerified:      { type: Boolean, default: false },
    businessVerified: { type: Boolean, default: false },
    avatarFileName:   { type: String, default: '' },
    avatarFilePath:   { type: String, default: '' },
    avatarDataUrl:    { type: String, default: '' },
    kycDocuments: {
      gstCertificateName:      { type: String, default: '' },
      gstCertificateType:      { type: String, default: '' },
      gstCertificateFilePath:  { type: String, default: '' },
      gstCertificateDataUrl:   { type: String, default: '' },
      panCardName:             { type: String, default: '' },
      panCardType:             { type: String, default: '' },
      panCardFilePath:         { type: String, default: '' },
      panCardDataUrl:          { type: String, default: '' },
      businessRegistrationName:{ type: String, default: '' },
      businessRegistrationType:{ type: String, default: '' },
      businessRegistrationFilePath:{ type: String, default: '' },
      businessRegistrationDataUrl:{ type: String, default: '' },
    },
  },
  // Set to true after partner completes the one-time profile setup wizard (post first payment)
  profileSetupComplete: { type: Boolean, default: false },
  createdBy:   { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
}, { timestamps: true });

module.exports = mongoose.model('Partner', PartnerSchema);
