const mongoose = require('mongoose');
const crypto   = require('crypto');

const SystemSchema = new mongoose.Schema({
  name:         { type: String, required: true, trim: true },
  tenantId:     { type: mongoose.Schema.Types.ObjectId, ref: 'Tenant', default: null, index: true },
  partnerId:    { type: mongoose.Schema.Types.ObjectId, ref: 'Partner', default: null, index: true },
  companyId:    { type: mongoose.Schema.Types.ObjectId, ref: 'Company',    required: true, index: true },
  departmentId: { type: mongoose.Schema.Types.ObjectId, ref: 'Department', required: true, index: true },
  agentType:    { type: String, enum: ['system', 'server', 'phone'], default: 'system', index: true },
  preferredPackageType: { type: String, enum: ['deb', 'rpm', 'exe', 'msi', 'macpkg', 'dmg', 'apk', 'solaris'], default: undefined },

  agentKey: {
    type:    String,
    default: () => crypto.randomBytes(32).toString('hex'),
    unique:  true,
    index:   true,
  },

  // Unique identity fields — used for duplicate-counting prevention
  agentId:  { type: String, index: true, sparse: true }, // UUID generated by agent on first run
  macAddress: { type: String, index: true, sparse: true }, // Primary NIC MAC
  velociraptorClientId: { type: String, index: true, sparse: true }, // Velociraptor client id, e.g. C.xxxx
  agentCertificateFingerprint256: { type: String, default: '', select: false },
  agentCertificateExpiresAt: { type: Date, default: null },
  agentCertificateSerial: { type: String, default: '', select: false },
  agentCertificateRevokedAt: { type: Date, default: null, select: false },

  // Updated by agent heartbeat
  hostname:     { type: String },
  ip:           { type: String },     // REQUIRED — reported each heartbeat
  osType:       { type: String },     // Windows / Linux / Darwin / Android
  os:           { type: String },     // Friendly name e.g. "Ubuntu 22.04"
  osVersion:    { type: String },
  arch:         { type: String },     // x86_64, arm64 etc.
  agentVersion: { type: String },     // e.g. "2.1.0"
  lastSeen:     { type: Date },

  status: {
    type:    String,
    enum:    ['pending', 'active', 'inactive', 'disconnected'],
    default: 'pending',
  },

  // EDR / module flags
  edrEnabled:      { type: Boolean, default: true },
  idsEnabled:      { type: Boolean, default: true },
  endpointIdsEnabled: { type: Boolean, default: true },
  packetSensorAvailable: { type: Boolean, default: false },
  packetIdsMode:     { type: String, default: '' },
  ipsEnforcementMode:{ type: String, default: '' },
  inlinePacketVerdict:{ type: Boolean, default: false },
  ipsEnabled:      { type: Boolean, default: true },
  firewallEnabled: { type: Boolean, default: true },
  yaraEnabled:     { type: Boolean, default: true },
  sandboxAnalysisEnabled: { type: Boolean, default: null },
  sandboxAnalysisStatus: { type: mongoose.Schema.Types.Mixed, default: {} },
  sandboxVmRunning: { type: Boolean, default: null },
  sandboxVmCount: { type: Number, default: 0, min: 0 },
  sandboxVmStatus: { type: mongoose.Schema.Types.Mixed, default: {} },
  wafEnabled:      { type: Boolean, default: true },
  networkMonitorEnabled: { type: Boolean, default: true },
  dnsSinkholeEnabled: { type: Boolean, default: true },
  dnsSinkholeTelemetryEnabled: { type: Boolean, default: true },
  dnsSinkholeEnforcementMode: { type: String, default: 'both' },
  dnsSinkholePolicyVersion: { type: Number, default: 0 },
  dnsCachePoisonEnabled: { type: Boolean, default: true },
  dnsCachePoisonTelemetryEnabled: { type: Boolean, default: true },
  dnsCachePoisonPolicyVersion: { type: Number, default: 0 },
  dnsCachePoisonStatus: { type: mongoose.Schema.Types.Mixed, default: {} },
  usbMonitorEnabled:     { type: Boolean, default: true },
  processMonitorEnabled: { type: Boolean, default: true },
  advancedProcessMonitorEnabled: { type: Boolean, default: true },
  containerMonitorEnabled: { type: Boolean, default: true },
  advancedProcessSensorStatus: { type: mongoose.Schema.Types.Mixed, default: {} },
  telemetrySensorStatus: { type: mongoose.Schema.Types.Mixed, default: {} },
  patchInventoryEnabled: { type: Boolean, default: true },
  memoryMonitorEnabled:  { type: Boolean, default: true },  // EDR cap #5 — memory activity scanner
  responseEnabled:       { type: Boolean, default: true },
  // Core agent controls are server-authoritative. Company roles never receive a
  // write API for these fields; only the platform superadmin can change them.
  securityControls: {
    selfProtection:        { type: Boolean, default: true },
    tamperProtection:      { type: Boolean, default: true },
    antiDebugging:         { type: Boolean, default: true },
    antiReverseEngineering:{ type: Boolean, default: true },
    antiDumpProtection:    { type: Boolean, default: true },
    integrityVerification: { type: Boolean, default: true },
    secureCommunication:   { type: Boolean, default: true },
    configurationEncryption:{ type: Boolean, default: true },
    certificateValidation: { type: Boolean, default: true },
    codeIntegrityMonitoring:{ type: Boolean, default: true },
    lockdownMode:          { type: Boolean, default: true },
    maintenanceMode:       { type: Boolean, default: false },
    protectionLevel:       { type: String, enum: ['standard', 'hardened', 'maximum'], default: 'hardened' },
    policyVersion:         { type: Number, default: 1 },
    updatedAt:             { type: Date, default: Date.now },
    updatedBy:             { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  },
  // Runtime self-protection posture reported by the installed endpoint agent.
  agentExpectedIntegrityHash: { type: String, default: '', maxlength: 64 },
  agentPendingIntegrityHash: { type: String, default: '', maxlength: 64 },
  agentReportedIntegrityHash: { type: String, default: '', maxlength: 64 },
  agentIntegrityStatus: {
    type: String,
    enum: ['unknown', 'verified', 'mismatch', 'missing', 'error'],
    default: 'unknown',
    index: true,
  },
  agentIntegrityCheckedAt: { type: Date, default: null },
  agentSecurityFindings: [{
    type: { type: String, maxlength: 48 },
    file: { type: String, maxlength: 260 },
    detail: { type: String, maxlength: 300 },
  }],
  agentDebuggerDetected: { type: Boolean, default: false },
  agentAnalysisTools: [{ type: String, maxlength: 64 }],
  agentSecurityLockdown: { type: Boolean, default: false, index: true },
  agentSecurityIncidentActive: { type: Boolean, default: false, index: true },
  agentSecurityLastEventAt: { type: Date, default: null },
  agentSecurityEventFingerprint: { type: String, default: '', maxlength: 64 },
  agentTransportSecurity: { type: mongoose.Schema.Types.Mixed, default: {} },
  geoEnrichmentEnabled:  { type: Boolean, default: true },
  geoFenceEnabled:       { type: Boolean, default: false },
  geoFenceLat:           { type: Number, default: null },
  geoFenceLon:           { type: Number, default: null },
  geoFenceRadiusMeters:  { type: Number, default: 200 },
  geoFenceLockOnViolation: { type: Boolean, default: false },
  geoFenceLastViolationAt: { type: Date, default: null },
  // Last native location state reported by this endpoint. This is mutable
  // current state (not event history), so a stationary agent remains visible
  // after the rolling alert window expires without resending identical GPS.
  gpsLat:              { type: Number, default: null },
  gpsLon:              { type: Number, default: null },
  gpsAccuracyMeters:   { type: Number, default: null },
  gpsAltitudeMeters:   { type: Number, default: null },
  gpsProvider:         { type: String, default: '' },
  gpsStatus:           { type: String, default: '' },
  gpsReason:           { type: String, default: '' },
  gpsObservedAt:       { type: Date, default: null, index: true },

  // How many times the agent bundle has been downloaded for this system
  downloadCount: { type: Number, default: 0 },

  // Set on the first heartbeat when the agent goes active
  installDate:  { type: Date, default: null },
  // FIM baseline: file monitoring starts from this time. Existing agents can be reset without changing installDate.
  fimStartAt:   { type: Date, default: null },

  blockedIps:  [{ type: String }],
  pendingCommands: [{ type: mongoose.Schema.Types.Mixed }],
  isActive:    { type: Boolean, default: true },

  // ── OTA agent update state (set by /agent/:id/update, cleared/advanced by heartbeat) ──
  updateStatus:        { type: String, enum: ['idle','pending','downloading','installing','success','failed'], default: 'idle' },
  updateRequestedAt:   { type: Date,   default: null },
  updateTargetVersion: { type: String, default: null },
  updateError:         { type: String, default: null },
  updateFinishedAt:    { type: Date,   default: null },

  // ── Isolation state (set by isolate/reconnect API) ────────────────────────
  isIsolated:      { type: Boolean, default: false },
  isolatedAt:      { type: Date, default: null },
  isolationReason: { type: String, default: null },
  isolationStatus: {
    type: String,
    enum: ['none', 'pending', 'isolated', 'reconnecting', 'failed'],
    default: 'none',
  },
  isolationCommandId: { type: String, default: null },
  isolationError:     { type: String, default: null },
  isolationSourceIp:  { type: String, default: null },
  isolationAttackType:{ type: String, default: null },
  isolationLastThreatAt: { type: Date, default: null },
  isolationAutoRecoverAt: { type: Date, default: null, index: true },
  isolationRecoveryAttempts: { type: Number, default: 0 },
  lastIpsCommand:     { type: mongoose.Schema.Types.Mixed, default: null },
  completedIpsCommandIds: [{ type: String }],
}, { timestamps: true });

// Compound index to detect duplicates
SystemSchema.index({ companyId: 1, macAddress: 1 }, { sparse: true });
SystemSchema.index({ companyId: 1, agentId: 1 },   { sparse: true });
SystemSchema.index({ tenantId: 1, companyId: 1, isActive: 1 });
SystemSchema.index({ companyId: 1, isActive: 1, ip: 1 });
SystemSchema.index({ companyId: 1, departmentId: 1, isActive: 1, lastSeen: -1 });
SystemSchema.index({ agentSecurityIncidentActive: 1, agentSecurityLastEventAt: -1 });

SystemSchema.pre('validate', async function (next) {
  if ((!this.tenantId || this.isModified('companyId')) && this.companyId) {
    const Company = require('./Company.model');
    const company = await Company.findById(this.companyId).select('tenantId partnerId').lean();
    if (company) {
      this.tenantId = company.tenantId || this.tenantId;
      this.partnerId = company.partnerId || null;
    }
  }
  next();
});

module.exports = mongoose.model('System', SystemSchema);
