export const ROLE_LABELS = {
  superadmin: 'Super Admin',
  partner_admin: 'Partner Admin',
  company_admin: 'Company Admin',
  department_admin: 'Department Admin',
  soc_manager: 'SOC Manager',
  l1_analyst: 'L1 Analyst',
  l2_analyst: 'L2 Analyst',
  l3_analyst: 'L3 Analyst',
  l4_analyst: 'L4 Threat Intelligence Analyst',
  analyst: 'Analyst'
};

export const DASHBOARD_ROUTES = {
  superadmin: '/dashboard/super-admin',
  partner_admin: '/partner/companies',
  company_admin: '/dashboard/company-admin',
  department_admin: '/department-admin/dashboard',
  soc_manager: '/soc-manager/dashboard',
  l1_analyst: '/l1/dashboard',
  l2_analyst: '/l2/dashboard',
  l3_analyst: '/l3/dashboard',
  l4_analyst: '/l4/dashboard',
  analyst: '/l1/dashboard'
};

export const ROLE_MENUS = {
  soc_manager: [
    { label: 'Overview', icon: '▦', to: '/soc-manager/dashboard' },
    { label: 'Profile Lock / Unlock', icon: '🔐', to: '/soc-manager/profile-locks' },
    { label: 'EDR System Setup', icon: '🛡', to: '/soc-manager/edrsystemstupe' },
    { label: 'Assigned Companies', icon: '🏢', to: '/soc-manager/companies' },
    { label: 'IDS', icon: '📡', to: '/soc-manager/ids' },
    { label: 'IPS', icon: '🛡️', to: '/soc-manager/ips' },
    { label: 'Firewall', icon: '🔥', to: '/soc-manager/firewall' },
    { label: 'SOAR Catalog', icon: '⚡', to: '/soc-manager/soar' },
    { label: 'Correlation', icon: '🔗', to: '/soc-manager/correlation' },
    { label: 'Analyst Management', icon: '👥', to: '/soc-manager/analysts' },
    { label: 'Shifts', icon: '◷', to: '/soc-manager/shifts' },
    { label: 'Assignment Queue', icon: '⇄', to: '/soc-manager/queue' },
    { label: 'Escalations', icon: '↗', to: '/soc-manager/escalations' },
    { label: 'Alerts', icon: '🔔', to: '/soc-manager/alerts' },
    { label: 'Tickets', icon: '🎟', to: '/soc-manager/tickets' },
    { label: 'Incidents', icon: '⚠️', to: '/soc-manager/incidents' },
    { label: 'Threat Intelligence', icon: '⌾', to: '/soc-manager/threat-intelligence' },
    { label: 'Contact Support', icon: '💬', to: '/soc-manager/contact-support' },
    { label: 'Reports', icon: '▤', to: '/soc-manager/reports' },
    { label: 'Audit', icon: '🛡', to: '/soc-manager/audit' },
    { label: 'Threat Audit', icon: '⌾', to: '/soc-manager/threat-audit' },
    { label: 'Profile', icon: '⚙', to: '/soc-manager/settings' }
  ],
  l1_analyst: [
    { label: 'Dashboard', icon: '▦', to: '/l1/dashboard' },
    { label: 'Shift Queue', icon: '◷', to: '/l1/shifts' },
    { label: 'Log', icon: '🔔', to: '/l1/alerts' },
    { label: 'My Tickets', icon: '🎟', to: '/l1/tickets' },
    { label: 'Incidents', icon: '⚠️', to: '/l1/incidents' },
    { label: 'Escalate to L2', icon: '↗', to: '/l1/escalations' },
    { label: 'Contact Support', icon: '💬', to: '/l1/contact-support' },
    { label: 'Audit', icon: '🛡', to: '/l1/audit' },
    { label: 'Profile', icon: '⚙', to: '/l1/settings' }
  ],
  l2_analyst: [
    { label: 'Dashboard', icon: '▦', to: '/l2/dashboard' },
    { label: 'Shift Queue', icon: '◷', to: '/l2/shifts' },
    { label: 'Log', icon: '🔎', to: '/l2/alerts' },
    { label: 'Escalated Alerts', icon: '↗', to: '/l2/escalations?direction=incoming' },
    { label: 'My Tickets', icon: '🎟', to: '/l2/tickets' },
    { label: 'Incident Details', icon: '⚠️', to: '/l2/incidents' },
    { label: 'Escalate to L3', icon: '🚀', to: '/l2/escalate-to-l3' },
    { label: 'Contact Support', icon: '💬', to: '/l2/contact-support' },
    { label: 'Audit', icon: '🛡', to: '/l2/audit' },
    { label: 'Profile', icon: '⚙', to: '/l2/settings' }
  ],
  l3_analyst: [
    { label: 'Dashboard', icon: '▦', to: '/l3/dashboard' },
    { label: 'Shift Queue', icon: '◷', to: '/l3/shifts' },
    { label: 'Log', icon: '🚨', to: '/l3/alerts?severity=critical' },
    { label: 'SOAR Playbooks', icon: '⚡', to: '/l3/soar' },
    { label: 'Correlation', icon: '🔗', to: '/l3/correlation' },
    { label: 'Incident', icon: '💥', to: '/l3/incidents' },
    { label: 'My Tickets', icon: '🎟', to: '/l3/tickets' },
    { label: 'Escalate', icon: '🚀', to: '/l3/escalate' },
    { label: 'Contact Support', icon: '💬', to: '/l3/contact-support' },
    { label: 'Reports', icon: '▤', to: '/l3/reports' },
    { label: 'Audit', icon: '🛡', to: '/l3/audit' },
    { label: 'Encryption Center', icon: '🔐', to: '/l3/encryption' },
    { label: 'Profile', icon: '⚙', to: '/l3/settings' }
  ],
  l4_analyst: [
    { label: 'Dashboard', icon: '▦', to: '/l4/dashboard' },
    { label: 'Shift Queue', icon: '◷', to: '/l4/shifts' },
    { label: 'Threat Intelligence Incidents', icon: '⌾', to: '/l4/incidents' },
    { label: 'Tickets', icon: '🎟', to: '/l4/tickets' },
    { label: 'IDS', icon: '📡', to: '/l4/ids' },
    { label: 'IPS', icon: '🛡️', to: '/l4/ips' },
    { label: 'Firewall', icon: '🔥', to: '/l4/firewall' },
    { label: 'Encryption Center', icon: '🔐', to: '/l4/encryption' },
    { label: 'Contact Support', icon: '💬', to: '/l4/contact-support' },
    { label: 'Audit', icon: '🛡', to: '/l4/audit' },
    { label: 'Profile', icon: '⚙', to: '/l4/settings' }
  ],
  company_admin: [
    { label: 'Dashboard', icon: '▦', to: '/dashboard/company-admin' },
    { label: 'Incidents', icon: '🚨', to: '/company-admin/incidents' },
    { label: 'Open Tickets', icon: '🎟', to: '/company-admin/alerts?status=open' },
    { label: 'Closed Tickets', icon: '✅', to: '/company-admin/alerts?status=resolved' },
    { label: 'Departments', icon: '🏛', to: '/company-admin/departments' },
    { label: 'Assets', icon: '💻', to: '/company-admin/systems' },
    { label: 'Users', icon: '👥', to: '/company-admin/users' },
    { label: 'Reports', icon: '▤', to: '/company-admin/reports' },
    { label: 'Notifications', icon: '◇', to: '/company-admin/settings?section=notifications' },
    { label: 'Company Settings', icon: '⚙', to: '/company-admin/settings' },
    { label: 'Encryption Center', icon: '🔐', to: '/company-admin/encryption' },
    { label: 'Profile', icon: '👤', to: '/company-admin/settings' }
  ],
  department_admin: [
    { label: 'Dashboard', icon: '▦', to: '/department-admin/dashboard' },
    { label: 'Department Incidents', icon: '🚨', to: '/alerts' },
    { label: 'Open Tickets', icon: '🎟', to: '/alerts?status=open' },
    { label: 'Closed Tickets', icon: '✅', to: '/alerts?status=resolved' },
    { label: 'Assets', icon: '💻', to: '/systems' },
    { label: 'Department Users', icon: '👥', to: '/team' },
    { label: 'Reports', icon: '▤', to: '/reports' },
    { label: 'Notifications', icon: '◇', to: '/department-admin/settings?section=notifications' },
    { label: 'Profile', icon: '👤', to: '/department-admin/settings' }
  ],
  partner_admin: [
    { label: 'Dashboard', icon: '▦', to: '/partner/companies' },
    { label: 'Companies', icon: '🏢', to: '/partner/companies' },
    { label: 'Company Incidents', icon: '🚨', to: '/alerts' },
    { label: 'Open Tickets', icon: '🎟', to: '/alerts?status=open' },
    { label: 'Closed Tickets', icon: '✅', to: '/alerts?status=resolved' },
    { label: 'Company Admins', icon: '👥', to: '/partner/users' },
    { label: 'Reports', icon: '▤', to: '/reports' },
    { label: 'Notifications', icon: '◇', to: '/settings?section=notifications' },
    { label: 'Audit Logs', icon: '☷', to: '/log-monitor' },
    { label: 'Partner Settings', icon: '⚙', to: '/settings' },
    { label: 'Profile', icon: '👤', to: '/settings' }
  ],
  superadmin: [
    { label: 'Dashboard', icon: '▦', to: '/dashboard/super-admin' },
    { label: 'Partners', icon: '🤝', to: '/partners' },
    { label: 'Companies', icon: '🏢', to: '/companies' },
    { label: 'Departments', icon: '🏛', to: '/departments' },
    { label: 'SOC Managers', icon: '🛡', to: '/soc-managers' },
    { label: 'L1 Analysts', icon: '👤', to: '/users?role=l1_analyst' },
    { label: 'L2 Analysts', icon: '🔍', to: '/users?role=l2_analyst' },
    { label: 'L3 Analysts', icon: '🚨', to: '/users?role=l3_analyst' },
    { label: 'All Incidents', icon: '⚠️', to: '/alerts' },
    { label: 'Assignment Queue', icon: '⇄', to: '/soc-workspace/queue' },
    { label: 'Escalations', icon: '↗', to: '/soc-workspace/escalations' },
    { label: 'SOAR', icon: '⚡', to: '/soar' },
    { label: 'Rules', icon: '⚙', to: '/ids?tab=rules' },
    { label: 'Integrations', icon: '🔌', to: '/settings?tab=integrations' },
    { label: 'Agents', icon: '💻', to: '/systems' },
    { label: 'Reports', icon: '▤', to: '/reports' },
    { label: 'Audit Logs', icon: '☷', to: '/log-monitor' },
    { label: 'System Health', icon: '♡', to: '/system-monitoring' },
    { label: 'Roles & Permissions', icon: '🔑', to: '/users' },
    { label: 'Settings', icon: '⚙', to: '/settings' }
  ]
};
