/**
 * DailyReportCard — shown on every dashboard.
 * - Fetches today's latest stored daily report
 * - Analyst: shows "Generate Report" button
 * - Auto-updates when report is generated
 */
import { useEffect, useState } from 'react';
import api from '../api/axios';
import { useAuth } from '../context/AuthContext';

const SEV_COLOR = { critical:'#f87171', high:'#f59e0b', medium:'#60a5fa', low:'#34d399' };
const CAT_ICON  = { malware:'🦠', network:'🌐', file:'📁', system:'🖥', edr:'👤', usb:'🔌', other:'📋' };

export default function DailyReportCard({ departmentId = null, companyApiPrefix = '' }) {
  // companyApiPrefix: '' for company users, '/daily-report/company/CID' for superadmin
  const { isAnalyst } = useAuth();
  const [report,    setReport]    = useState(null);
  const [loading,   setLoading]   = useState(true);
  const [generating,setGenerating]= useState(false);
  const [error,     setError]     = useState('');

  const today = new Date().toISOString().slice(0, 10);

  const load = async () => {
    setLoading(true);
    try {
      const base = companyApiPrefix || '/daily-report';
      const q    = departmentId ? `?departmentId=${departmentId}` : '';
      const { data } = await api.get(`${base}/latest${q}`);
      setReport(data);
    } catch {
      setReport(null);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, [departmentId]);

  const generate = async () => {
    setGenerating(true); setError('');
    try {
      const base = companyApiPrefix ? `${companyApiPrefix}/generate` : '/daily-report/generate';
      const { data } = await api.post(base, {
        date: today,
        ...(departmentId ? { departmentId } : {}),
      });
      setReport(data);
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to generate report');
    } finally {
      setGenerating(false);
    }
  };

  const s = {
    card: {
      background: '#0c1a2e', border: '1px solid #1e3a5f',
      borderRadius: 10, padding: '18px 20px', marginTop: 20,
    },
    header: {
      display: 'flex', justifyContent: 'space-between',
      alignItems: 'center', marginBottom: 14,
    },
    title: { fontSize: 14, fontWeight: 600, color: '#93c5fd' },
    date:  { fontSize: 11, color: '#1e40af' },
    genBtn: {
      fontSize: 11, padding: '5px 14px', borderRadius: 6,
      border: 'none', cursor: generating ? 'not-allowed' : 'pointer',
      background: generating ? '#1e3a5f' : '#2563eb',
      color: '#fff',
    },
    grid: {
      display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(110px,1fr))', gap: 8,
      marginBottom: 14,
    },
    statBox: {
      background: '#060e1a', borderRadius: 7,
      padding: '10px 12px', textAlign: 'center',
    },
    bigNum: { fontSize: 22, fontWeight: 700 },
    label:  { fontSize: 10, color: '#1e40af', marginTop: 2 },
    row:    { display: 'flex', gap: 8, marginBottom: 6, alignItems: 'center' },
    bar:    (pct, color) => ({
      flex: 1, height: 8, background: '#1e3a5f', borderRadius: 4, overflow: 'hidden',
    }),
    fill: (pct, color) => ({
      width: `${pct}%`, height: '100%', background: color,
      borderRadius: 4, minWidth: 3, transition: 'width .5s ease',
    }),
  };

  if (loading) return (
    <div style={s.card}>
      <div style={s.header}>
        <span style={s.title}>📊 Daily Report</span>
      </div>
      <p style={{ color: '#1e3a5f', fontSize: 13 }}>Loading…</p>
    </div>
  );

  const isToday = report?.date === today;

  return (
    <div style={s.card}>
      <div style={s.header}>
        <div>
          <div style={s.title}>📊 Daily Report Card</div>
          {report && (
            <div style={s.date}>
              {report.date} · Generated by {report.generatedBy === 'auto' ? '🤖 Auto' : '👤 Analyst'}
              {!isToday && <span style={{ color: '#f59e0b', marginLeft: 8 }}>⚠ Yesterday's data</span>}
            </div>
          )}
        </div>
        {/* Analyst can manually generate */}
        {(isAnalyst || companyApiPrefix) && (
          <button onClick={generate} disabled={generating} style={s.genBtn}>
            {generating ? 'Generating…' : '⚡ Generate Report'}
          </button>
        )}
      </div>

      {error && <div style={{ color:'#fca5a5', fontSize:12, marginBottom:10 }}>{error}</div>}

      {!report ? (
        <div style={{ color: '#1e3a5f', fontSize: 13 }}>
          No report yet for today.{' '}
          {(isAnalyst || companyApiPrefix) && (
            <span
              onClick={generate}
              style={{ color: '#2563eb', cursor: 'pointer', textDecoration: 'underline' }}
            >
              Generate now
            </span>
          )}
        </div>
      ) : (
        <>
          {/* Summary stat boxes */}
          <div style={s.grid}>
            {[
              { label: 'Total Alerts', value: report.summary?.totalAlerts ?? 0,  color: '#60a5fa' },
              { label: 'Critical',     value: report.summary?.critical     ?? 0,  color: '#f87171' },
              { label: 'High',         value: report.summary?.high         ?? 0,  color: '#f59e0b' },
              { label: 'Avg Resolve',  value: report.summary?.avgResolutionMinutes != null
                  ? `${report.summary.avgResolutionMinutes}m` : 'N/A',            color: '#34d399' },
            ].map(({ label, value, color }) => (
              <div key={label} style={s.statBox}>
                <div style={{ ...s.bigNum, color }}>{value}</div>
                <div style={s.label}>{label}</div>
              </div>
            ))}
          </div>

          {/* Category breakdown bars */}
          {report.byCategory?.length > 0 && (
            <div style={{ marginBottom: 12 }}>
              <div style={{ fontSize: 11, color: '#1e40af', marginBottom: 6 }}>By category:</div>
              {report.byCategory.slice(0, 5).map(({ category, count }) => {
                const max = Math.max(...report.byCategory.map(c => c.count), 1);
                return (
                  <div key={category} style={s.row}>
                    <span style={{ fontSize: 11, width: 70, color: '#60a5fa' }}>
                      {CAT_ICON[category] || '📋'} {category}
                    </span>
                    <div style={s.bar()}>
                      <div style={s.fill((count / max) * 100, '#2563eb')} />
                    </div>
                    <span style={{ fontSize: 11, color: '#93c5fd', width: 28, textAlign: 'right' }}>
                      {count}
                    </span>
                  </div>
                );
              })}
            </div>
          )}

          {/* Severity pills */}
          {report.bySeverity?.length > 0 && (
            <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
              {report.bySeverity.map(({ severity, count }) => (
                <span key={severity} style={{
                  fontSize: 11, padding: '2px 10px', borderRadius: 999,
                  background: (SEV_COLOR[severity] || '#1e3a5f') + '22',
                  border: `1px solid ${(SEV_COLOR[severity] || '#1e3a5f')}66`,
                  color: SEV_COLOR[severity] || '#93c5fd',
                }}>
                  {severity} {count}
                </span>
              ))}
            </div>
          )}
        </>
      )}
    </div>
  );
}
