const escape = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));

function loginPage({ stage, csrf, recipient, sent, message = '' }) {
  const otp = stage === 'otp';
  const maskedEmail = String(recipient).replace(/^(.{1,2})[^@]*(@.*)$/, '$1***$2');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${otp ? 'Verify OTP' : 'Sign in'} · AJNAT Kafka</title><style>
  *{box-sizing:border-box}body{margin:0;background:#0b101b;color:#e9eef7;font:15px system-ui,sans-serif;min-height:100vh;display:grid;place-items:center;padding:24px}main{width:100%;max-width:420px;padding:32px;border:1px solid #2a3549;border-radius:16px;background:#141d2d;box-shadow:0 24px 70px #0005}.brand{color:#9eacff;font-weight:700;letter-spacing:2px;font-size:12px}h1{font-size:25px;margin:16px 0 8px}p{color:#b3bfd2;line-height:1.6}label{display:block;margin:20px 0 8px;font-weight:600}input,button{width:100%;padding:13px;border-radius:8px;font:inherit}input{border:1px solid #43516a;background:#0b1321;color:#fff}input:focus{outline:2px solid #8999ff;outline-offset:2px}button{margin-top:24px;border:0;background:#8d9aff;color:#101627;font-weight:700;cursor:pointer}button:hover{background:#a5afff}.error{padding:12px;background:#44222c;color:#ffd3d9;border-radius:8px}.resend{margin-top:12px;background:transparent;color:#bbc7ff;border:1px solid #43516a}a{color:#bbc7ff}.back{text-align:center;font-size:13px}.otp{font-size:26px;text-align:center;letter-spacing:9px}.foot{font-size:12px;margin-bottom:0}
  </style></head><body><main><div class="brand">AJNAT / KAFKA</div><h1>${otp ? 'Verify your email' : 'Sign in to Kafka'}</h1><p>${otp ? (sent ? `Enter the 6-digit OTP sent to <strong>${escape(maskedEmail)}</strong>.` : `Request a new OTP for <strong>${escape(maskedEmail)}</strong> to continue.`) : 'Use your Kafka UI username and password. We will email you a verification code for every login.'}</p>${message ? `<p class="error" role="alert">${escape(message)}</p>` : ''}<form method="post" action="${otp ? '/login/otp' : '/login'}"><input type="hidden" name="csrf" value="${escape(csrf)}">${otp ? '<label for="otp">Email OTP</label><input class="otp" id="otp" name="otp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" minlength="6" maxlength="6" placeholder="000000" required autofocus>' : '<label for="username">Username</label><input id="username" name="username" autocomplete="username" required autofocus><label for="password">Password</label><input id="password" name="password" type="password" autocomplete="current-password" required>'}<button type="submit">${otp ? 'Verify & sign in' : 'Continue'}</button></form>${otp ? `<form method="post" action="/login/resend"><input type="hidden" name="csrf" value="${escape(csrf)}"><button class="resend" type="submit">Resend OTP</button></form><p class="back"><a href="/logout">Back to sign in</a></p>` : ''}<p class="foot">${otp ? 'OTP expires in 10 minutes. Check your inbox or spam folder. You can resend after 60 seconds.' : 'Your session expires after 30 minutes of inactivity.'}</p></main></body></html>`;
}

module.exports = { loginPage };
